from main import *

studentID = (input("Enter the student ID: "))
numMajor = int(input("How many major grades will you be entering?: "))
majorGrades = (createMajor(numMajor))
numMinor = int(input("How many minor grades will you be entering?: "))
minorGrades = (createMinor(numMinor))
numOther = int(input("How many other grades will you be entering?: "))
otherGrades = (createOther(numOther))
print()
print("Student ID: " + studentID)
print("Major Grades: " + str(majorGrades))
print("Minor Grades: " + str(minorGrades))
print("Other Grades: " + str(otherGrades))
majorAvg = calcMajorAvg(majorGrades)
minorAvg = calcMinorAvg(minorGrades)
otherAvg = calcOtherAvg(otherGrades)
print("Major Average: " + str(majorAvg))
print("Minor Average: " + str(minorAvg))
print("Other Average: " + str(otherAvg))
sixWeeksAvg = calcSixWeeksAvg(majorAvg, minorAvg, otherAvg)
print("Six Weeks Average: " + str(sixWeeksAvg))
